### ISSUE TITLE
Partial Dependence Plot: Fix seed

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#43] opened 2023-04-12 08:56 UTC
There seems to be a problem with the reproducibility of the Partial Dependence Plot that needs to be checked.

**Comment by sarah-segel** [comment] 2024-02-09 11:30
Should be checked if this is still the case, i.e. use the API to produce PDP plots and check if the results are reproducible.

**Comment by alexandertornede** [comment] 2024-02-19 12:40
Seems to be fixed with #85 . Cannot reproduce the problem anymore. All plots are identical for me.

**Closed by alexandertornede** 2024-02-19 12:40 UTC
Labels: bug
